### ISSUE TITLE
Menu Bar does not show up with BehaviorTree gui. 

### ISSUE THREAD

**Issue by PeaceSells50** [BadBehavior/BadBehavior_T3D#1]
When it exits the Behavior Tree gui it destroys the Menu Bar belonging to the World Editor.

**Comment by PeaceSells50** [comment]
I probably should have mentioned. Torque3d 3.7 development. PC. 32 bit.

**Comment by GuyAllard** [comment]
Hi, thanks for the report.
It would be helpful if you can supply step-by-step details so that I can reproduce the conditions on my machine.

**Comment by PeaceSells50** [comment]
So I don't if i caused it by changing the hotkey to SHIFT F9 or maybe it
happened when I merged stuff. .But as soon as i hit the hotkey and it
triggers toggleBevaviorTreeEditor() and it creates the new canvas their is
no menu bar visible. I think something goes wrong in the menubar attach( it
seems to be attaching to the worldeditor canvas. just sticks it on the end
of the world editor menu ). and when you hit the hotkey to leave and it
calls destroy menubar it destroys the both the world editor menubar and the
menubar for the behavior tree.

Guy, thank you  for providing such a wonderful tool!

The Torque3d community is stunning to watch in action.

**Comment by PeaceSells50** [comment]
Have you been able to reproduce the bug or should I continue to look on my
side?

**Comment by PeaceSells50** [comment]
I wish I understood torque better, but there seems to be a lot of places
using Canvas when it seems like it should be BTEditCanvas. Am I just not
understanding?

**Comment by GuyAllard** [comment]
When you open the editors, the gui for that editor becomes the canvas. 

I have noticed that the menu bar handling by Torque is not reliable.
If I open the world editor (F11) then open the gui editor (F10), then exit the gui editor (F10), this results in the world editor menu bar disappearing.
For now, the safest option is not to open the behavior tree editor from inside of the world editor.
